In [3]:
from joblib import load
import pandas as pd
import numpy as np
import streamlit as st
import tensorflow as tf
from keras.preprocessing import image

In [2]:
model_premium = load("svr_premium_model.joblib")
input_sc = load("sc_input_premium")
output_sc = load("sc_output_premium")

In [3]:
prediction_data = input_sc.transform([[1230.0, 80.0, 28, 80.0, 24.0, 20.0]])
print(prediction_data)

[[ 0.95524034  1.22195037 -0.81386216  1.39428701  1.47732437  1.07264244]]


In [4]:
output_sc.inverse_transform([(model_premium.predict(prediction_data))])

array([[11.60207144]])

In [6]:
st.title("first try :tree:")

2024-08-26 16:58:59.195 
  command:

    streamlit run C:\Users\tharu\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]


DeltaGenerator()

In [3]:
x = [[2]]
x[0][0]

2

In [2]:
model_poor = load("rfr_user_model.joblib")
input_ct = load("ct_output_poor")
output_sc = load("sc_input_poor")

In [10]:
data = pd.DataFrame([[1990, 'Chhattisgarh', 'Durg', 397.90]], 
                    columns=['Year', 'State Name', 'Dist Name', 'RICE AREA (1000 ha)'])
data
filtered_data = input_ct.transform(data)
filtered_data[0][:1]

array([0.])

In [15]:
ans = model_poor.predict(filtered_data)
output_sc.inverse_transform([ans])

array([[1207.67]])

In [16]:
k = states = ['Chhattisgarh','Maharashtra','Punjab','Gujarat','Himachal Pradesh','West Bengal','Assam','Kerala','Haryana','Bihar','Uttar Pradesh','Jharkhand','Uttarakhand',
 'Telangana',
 'Karnataka',
 'Rajasthan',
 'Tamil Nadu',
 'Madhya Pradesh',
 'Orissa',
 'Andhra Pradesh']

In [17]:
len(k)

20

CNN MODEL

In [2]:
cnn = tf.keras.models.load_model("mobilenet.h5")

In [5]:
test_image =image.load_img(r"E:\wheat disease\data\val\Healthy\Healthy057.jpg", target_size = (224, 224))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
print(test_image.shape)
result = cnn.predict(test_image)
print(result[0][1])

(1, 224, 224, 3)
1/1 [==============================] - 0s 102ms/step
1.0
