In [25]:
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
import keras_tuner as kt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
import numpy as np

In [2]:
df = pd.read_csv(r"E:\Dataset\ICRISAT-District Level Data.csv")
df.head()

Dist Code  Year  State Code    State Name Dist Name  RICE AREA (1000 ha)  \
0          1  1990          14  Chhattisgarh      Durg                397.9   
1          1  1991          14  Chhattisgarh      Durg                393.2   
2          1  1992          14  Chhattisgarh      Durg                398.4   
3          1  1993          14  Chhattisgarh      Durg                410.2   
4          1  1994          14  Chhattisgarh      Durg                430.1   

   RICE YIELD (Kg per ha)  
0                  1210.0  
1                  1293.0  
2                  1291.0  
3                  1387.0  
4                  1399.0

In [3]:
unwanted = ["Dist Code", "State Code"]
df = df.drop(unwanted, axis=1)

In [4]:
X = df.iloc[:, :4].values
X
y = df.iloc[:, -1].values
y.reshape(-1, 1)

array([[1210.  ],
       [1293.  ],
       [1291.  ],
       ...,
       [3388.63],
       [3338.59],
       [2653.18]])

In [5]:
# le = LabelEncoder()
# ct = ColumnTransformer(transformers=[
#     ("encoder", OneHotEncoder(sparse_output=False), ["State Name", "Dist Name"]),
#     ("scaler", StandardScaler(), ["Year", "RICE AREA (1000 ha)"])
#     ], remainder="passthrough")
# X = ct.fit_transform(X)

In [6]:
# sc = StandardScaler()
# y = sc.fit_transform(y.reshape(-1, 1))

In [14]:
X[:, 2]

array(['Durg', 'Durg', 'Durg', ..., 'Warangal Urban', 'Mahabubabad',
       'Mahabubabad'], dtype=object)

In [13]:
le = LabelEncoder()
le1 = LabelEncoder()
X[:, 1] = le.fit_transform(X[:, 1])

In [15]:
X[:, 2] = le1.fit_transform(X[:, 2])

In [16]:
sc = StandardScaler()
X = s

array([1990, 3, 162, 397.9], dtype=object)

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

array([2016.  ,   15.  ,  426.  ,   69.14], dtype=float32)

In [34]:
def model():
    ann = tf.keras.models.Sequential()
    ann.add(tf.keras.layers.Dense(
        units=6,
        activation="relu",
        input_shape = (4,)
    ))
    ann.add(tf.keras.layers.Dense(
        units=6,
        activation="relu"
    ))
    # ann.add(tf.keras.layers.Dense(
    #     units=128,
    #     activation="relu"
    # ))
    ann.add(tf.keras.layers.Dense(
        units=1,
        activation="linear"
    ))
    ann.compile(
        optimizer="rmsprop",
        loss="mean_squared_error",
        metrics=["accuracy"]
    )

    return ann

In [35]:
models = model()

In [36]:
models.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_8 (Dense)             (None, 6)                 30        
                                                                 
 dense_9 (Dense)             (None, 6)                 42        
                                                                 
 dense_10 (Dense)            (None, 1)                 7         
                                                                 
Total params: 79 (316.00 Byte)
Trainable params: 79 (316.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [38]:
X_train = np.array(X_train).astype('float32')
X_test = np.array(X_test).astype('float32')

# Convert labels to int32 or float32 (depends on your problem type, e.g., regression or classification)
y_train = np.array(y_train).astype('int32')
y_test = np.array(y_test).astype('int32')

In [39]:
models.fit(X_train, y_train, batch_size=32, epochs=10, validation_data=(X_test, y_test))

Epoch 1/10
350/350 [==============================] - 1s 1ms/step - loss: 1195304.1250 - accuracy: 0.0000e+00 - val_loss: 1111685.0000 - val_accuracy: 0.0000e+00
Epoch 2/10
350/350 [==============================] - 0s 1ms/step - loss: 1099262.5000 - accuracy: 0.0000e+00 - val_loss: 1073164.0000 - val_accuracy: 0.0000e+00
Epoch 3/10
350/350 [==============================] - 0s 1ms/step - loss: 1078311.7500 - accuracy: 0.0000e+00 - val_loss: 1074360.0000 - val_accuracy: 0.0000e+00
Epoch 4/10
350/350 [==============================] - 1s 1ms/step - loss: 1073559.2500 - accuracy: 0.0000e+00 - val_loss: 1064099.8750 - val_accuracy: 0.0000e+00
Epoch 5/10
350/350 [==============================] - 0s 1ms/step - loss: 1072544.2500 - accuracy: 0.0000e+00 - val_loss: 1061246.7500 - val_accuracy: 0.0000e+00
Epoch 6/10
350/350 [==============================] - 0s 1ms/step - loss: 1071512.6250 - accuracy: 0.0000e+00 - val_loss: 1062054.2500 - val_accuracy: 0.0000e+00
Epoch 7/10
350/350 [========

In [40]:
from sklearn.ensemble import RandomForestClassifier
rc = RandomForestClassifier(n_estimators=100)
rc.fit(X_train, y_train)

RandomForestClassifier()

In [41]:
from sklearn.metrics import accuracy_score
y_pred = rc.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.0916577157178661


In [ ]:
33