In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from joblib import load, dump

In [2]:
df = pd.read_csv(r"E:\Dataset\crop yield data sheet.csv")

In [3]:
df = df.dropna()
df.head(-5)

Rain Fall (mm)  Fertilizer Temperatue  Nitrogen (N)  Phosphorus (P)  \
0           1230.0        80.0         28          80.0            24.0   
1            480.0        60.0         36          70.0            20.0   
2           1250.0        75.0         29          78.0            22.0   
3            450.0        65.0         35          70.0            19.0   
4           1200.0        80.0         27          79.0            22.0   
..             ...         ...        ...           ...             ...   
89           410.0        52.0         40          62.0            19.0   
90          1225.0        75.0         28          75.0            23.0   
91           460.0        60.0         39          60.0            20.0   
92          1150.0        78.0         29          77.0            21.0   
93           475.0        65.0         38          60.0            20.0   

    Potassium (K)  Yeild (Q/acre)  
0            20.0            12.0  
1            18.0             8.0  
2            19.0            11.0  
3            18.0             9.0  
4            19.0            11.0  
..            ...             ...  
89           16.0             7.0  
90           20.0            11.0  
91           16.0             7.0  
92           18.0             9.0  
93           16.0             8.0  

[94 rows x 7 columns]

In [9]:
X = df.iloc[:, :-1].values
print(X[0])
y = df.iloc[:, -1].values

print(y[0])

[1230.0 80.0 '28' 80.0 24.0 20.0]
12.0


In [5]:
y = y.reshape(-1, 1)
y[0]

array([12.])

In [6]:
sc = StandardScaler()
sc1 = StandardScaler()
X = sc.fit_transform(X)
print(X[0])
y = sc1.fit_transform(y)
print(y[0])

[ 0.95524034  1.22195037 -0.81386216  1.39428701  1.47732437  1.07264244]
[1.49341363]


In [7]:
dump(sc, "sc_input_premium")
dump(sc1, "sc_output_premium")

['sc_output_premium']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=42)

In [8]:
svm = SVR(kernel='rbf')
svm.fit(X_train, y_train)

C:\Users\tharu\Lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [10]:
dump(svm, 'svr_premium_model.joblib')

['svr_premium_model.joblib']

In [43]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
y_pred = svm.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)


print(f"Mean Absolute Error : {mean_absolute_error(y_test, y_pred)}")
print(f"Mean Squared Error : {mean_squared_error(y_test, y_pred)}")
print(f"Root Mean Squared Error : {np.sqrt(mse)}")
print(f"R² Score: {r2_score(y_test, y_pred)}")

Mean Absolute Error : 0.24891300175097647
Mean Squared Error : 0.12233534105112195
Root Mean Squared Error : 0.34976469383161296
R² Score: 0.9005734991131271


In [58]:
val = svm.predict([X_test[18]])
sc1.inverse_transform(val.reshape(-1, 1))

array([[10.71500521]])

In [55]:
X_test[18]

array([ 0.8798667 ,  0.72081911, -0.81386216,  0.94270223,  0.96234158,
        0.51956118])

In [60]:
sc1.inverse_transform(y_test[18].reshape(-1, 1))

array([[11.]])